### ISSUE TITLE
Player with black bars on the sides

### ISSUE THREAD

**Issue by pqray** [clappr/clappr#1268]
Boa tarde. Gostaria de uma ajuda para o meu player que fica com essas barras laterais ao lado.

A parte do código:

![capturar](https://cloud.githubusercontent.com/assets/19388488/22385320/4ee37734-e4b9-11e6-8a7b-98d0ff1c8268.JPG)

**Comment by pqray** [comment]
site: http://sejamaiorlab.web2335.uni5.net/diferencial_criativa/

**Comment by thiagopnts** [comment]
no css da pagina vc pode fazer isso:
```css
video {
   object-fit: fill;
}
```

**Comment by towerz** [comment]
@thiagopnts @pqray talvez seja melhor usar
```css
video {
    object-fit: cover;
}
```
Dessa forma não há distorção da imagem devido à mudança de aspecto
