### ISSUE TITLE
Github Star button is not clickable in the site (http://clappr.io/).

### ISSUE THREAD

**Issue by renanvaz** [clappr/clappr#226]
Adjust the z-index of the .container class.

``` css
.container {
    position: absolute;
    text-align: center;
    width: 100%;
    margin: 0 auto;
    top: 15%;
    z-index: 1;
}
```
