### ISSUE TITLE
Migrate travis from legacy to container-based travis 

### ISSUE THREAD

**Issue by leandromoreira** [clappr/clappr#529]
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by leandromoreira** [comment]
I tried the simplest change but it didn't work, it requires further investigation.

```yaml
 sudo: false
  language: node_js
  node_js:
    - "0.12"
 addons:
   apt:
     sources:
     - ubuntu-toolchain-r-test
     packages:
     - gcc-4.8
     - g++-4.8
  before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

  install:
    - "npm install"

  env:
```

With above modification travis won't start Chrome.

```
24 08 2015 17:30:54.316:INFO [karma]: Karma v0.13.9 server started at http://localhost:9876/
24 08 2015 17:30:54.328:INFO [launcher]: Starting browser Chrome
24 08 2015 17:30:55.077:ERROR [launcher]: Cannot start Chrome
	
24 08 2015 17:30:55.087:INFO [launcher]: Trying to start Chrome again (1/2).
24 08 2015 17:30:55.498:ERROR [launcher]: Cannot start Chrome
	
24 08 2015 17:30:55.501:INFO [launcher]: Trying to start Chrome again (2/2).
24 08 2015 17:30:55.835:ERROR [launcher]: Cannot start Chrome
	
24 08 2015 17:30:55.836:ERROR [launcher]: Chrome failed 2 times (cannot start). Giving up.
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```
